import os
import logging
import asyncio
import base64
import tempfile
import aiohttp
import sys
import time
import subprocess
import signal
import urllib.request
import urllib.error
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger('integrations.stable_diffusion')

# Default API URL for local Stable Diffusion WebUI (AUTOMATIC1111)
SD_API_URL = os.getenv("STABLE_DIFFUSION_API_URL", "http://localhost:7860")

async def generate_local_image(prompt: str) -> dict:
    """
    Sends a request to the local Stable Diffusion WebUI API to generate an image
    using the epiCRealism model.
    Saves the generated image to a temporary file and returns a dict with status and file path.
    """
    logger.info(f"Generating image for prompt: '{prompt}'")
    
    url = f"{SD_API_URL}/sdapi/v1/txt2img"
    
    # epiCRealism / SD 1.5 optimized defaults
    payload = {
        "prompt": f"{prompt}, photorealistic, hyperrealistic, highly detailed, sharp focus, 8k resolution, raw photo",
        "negative_prompt": "ugly, deformed, bad eyes, bad anatomy, bad hands, extra limbs, blurry, low quality, duplicate, cartoon, drawing, painting, 3d render, saturated",
        "steps": 25,
        "cfg_scale": 6.0,
        "width": 512,
        "height": 512,
        "sampler_name": "DPM++ 2M Karras",
        "restore_faces": False
    }
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=payload, timeout=120) as response:
                if response.status != 200:
                    text = await response.text()
                    logger.error(f"Stable Diffusion API returned status {response.status}: {text}")
                    return {
                        "status": "error",
                        "message": f"Stable Diffusion API returned status {response.status}."
                    }
                
                data = await response.json()
                images = data.get("images", [])
                if not images:
                    logger.error("Stable Diffusion API response contained no images.")
                    return {
                        "status": "error",
                        "message": "No images were generated by the API."
                    }
                
                # Decode the base64 image data
                img_data = base64.b64decode(images[0])
                
                # Write to a temporary file
                with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as temp_file:
                    temp_file.write(img_data)
                    temp_path = temp_file.name
                
                logger.info(f"Successfully generated image and saved to: {temp_path}")
                return {
                    "status": "success",
                    "image_path": temp_path,
                    "message": "Image generated successfully. The image has been uploaded to the Discord channel."
                }
                
    except asyncio.TimeoutError:
        logger.error("Timeout connecting to Stable Diffusion API.")
        return {
            "status": "error",
            "message": "Image generation timed out. Please check if the Stable Diffusion server is busy."
        }
    except aiohttp.ClientConnectorError as e:
        logger.error(f"Connection error to Stable Diffusion API: {e}")
        return {
            "status": "error",
            "message": f"Failed to connect to the Stable Diffusion API at {SD_API_URL}. Ensure it is running with the --api flag enabled."
        }
    except Exception as e:
        logger.error(f"Unexpected error during image generation: {e}")
        return {
            "status": "error",
            "message": f"An unexpected error occurred: {str(e)}"
        }

def start_stable_diffusion_server() -> Optional[subprocess.Popen]:
    """
    Starts the local Stable Diffusion WebUI server as a subprocess
    if START_STABLE_DIFFUSION_SERVER is enabled in the environment.
    Polls the server API until it becomes responsive.
    Returns the subprocess.Popen object if started, else None.
    """
    start_server = os.getenv("START_STABLE_DIFFUSION_SERVER", "false").lower() == "true"
    if not start_server:
        logger.info("START_STABLE_DIFFUSION_SERVER is false. Skipping server startup.")
        return None
        
    cmd = os.getenv("STABLE_DIFFUSION_START_COMMAND")
    if not cmd:
        logger.error("START_STABLE_DIFFUSION_SERVER is true, but STABLE_DIFFUSION_START_COMMAND is not set.")
        return None
        
    cwd = os.getenv("STABLE_DIFFUSION_WORKING_DIR") or None
    if cwd and not os.path.isdir(cwd):
        logger.error(f"STABLE_DIFFUSION_WORKING_DIR directory does not exist: {cwd}")
        return None
        
    logger.info(f"Starting Stable Diffusion server with command: {cmd}")
    if cwd:
        logger.info(f"Working directory: {cwd}")
        
    # Cross-platform process group execution
    popen_kwargs = {}
    if sys.platform != "win32":
        popen_kwargs["preexec_fn"] = os.setsid
    else:
        popen_kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
        
    try:
        # Redirect stdout and stderr to a log file to keep console clean
        log_path = os.path.join(os.path.dirname(__file__), "..", "..", "stable_diffusion_server.log")
        log_file = open(log_path, "a", encoding="utf-8")
        log_file.write(f"\\n--- Server started at {time.strftime('%Y-%m-%d %H:%M:%S')} ---\\n")
        
        proc = subprocess.Popen(
            cmd,
            shell=True,
            stdout=log_file,
            stderr=log_file,
            cwd=cwd,
            **popen_kwargs
        )
        # log_file will be closed in the parent process by python GC, but stays open in the child
    except Exception as e:
        logger.error(f"Failed to start Stable Diffusion server: {e}")
        return None
        
    # Poll the API URL until ready
    url = os.getenv("STABLE_DIFFUSION_API_URL", "http://localhost:7860")
    logger.info(f"Waiting for Stable Diffusion server to become ready at {url}...")
    
    timeout = 180  # 3 minutes default
    poll_interval = 3
    elapsed = 0
    ready = False
    
    while elapsed < timeout:
        if proc.poll() is not None:
            logger.error(f"Stable Diffusion process exited prematurely with code {proc.returncode}. Check stable_diffusion_server.log for details.")
            break
            
        try:
            req = urllib.request.Request(f"{url}/sdapi/v1/options", method="GET")
            with urllib.request.urlopen(req, timeout=2) as response:
                if response.status == 200:
                    ready = True
                    break
        except Exception:
            pass
            
        time.sleep(poll_interval)
        elapsed += poll_interval
        print(".", end="", flush=True)
        
    print()  # Newline after dots
    
    if ready:
        logger.info("Stable Diffusion server is ready for image generation!")
    else:
        logger.warning("Stable Diffusion server did not become ready within the timeout period. Image generation may fail until it is fully loaded.")
        
    return proc

def stop_stable_diffusion_server(proc: subprocess.Popen):
    """
    Gracefully terminates the Stable Diffusion server subprocess and its process group.
    """
    if not proc or proc.poll() is not None:
        return
        
    logger.info("Stopping Stable Diffusion server process...")
    
    if sys.platform != "win32":
        try:
            pgid = os.getpgid(proc.pid)
            os.killpg(pgid, signal.SIGTERM)
            logger.info(f"Sent SIGTERM to process group {pgid}")
        except ProcessLookupError:
            pass
        except Exception as e:
            logger.error(f"Error terminating process group: {e}")
    else:
        try:
            proc.send_signal(signal.CTRL_BREAK_EVENT)
            logger.info("Sent CTRL_BREAK_EVENT to Windows process group")
        except Exception as e:
            logger.error(f"Error sending signal to process: {e}")
            proc.terminate()
            
    try:
        proc.wait(timeout=10)
        logger.info("Stable Diffusion server stopped successfully.")
    except subprocess.TimeoutExpired:
        logger.warning("Stable Diffusion server did not exit in 10 seconds. Forcing shutdown...")
        if sys.platform != "win32":
            try:
                pgid = os.getpgid(proc.pid)
                os.killpg(pgid, signal.SIGKILL)
                logger.info(f"Sent SIGKILL to process group {pgid}")
            except ProcessLookupError:
                pass
            except Exception as e:
                logger.error(f"Error forcing shutdown: {e}")
        else:
            proc.kill()
            logger.info("Forced process kill on Windows.")
